# Generated by Django 5.2.1 on 2025-05-31 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('BONUS_VOLUME', 'Bonificación por volumen'), ('BONUS_AMOUNT', 'Bonificación por monto'), ('DISCOUNT_VOLUME', 'Descuento por volumen')], max_length=20)),
                ('channel', models.CharField(choices=[('MAYORISTA', 'Mayorista'), ('COBERTURA', 'Cobertura'), ('MERCADO', 'Mercado'), ('INSTITUCIONAL', 'Institucional')], max_length=20)),
                ('product_code', models.CharField(max_length=50)),
                ('quantity_required', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_required', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus_products', models.JSONField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_scaled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CoreScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.PositiveIntegerField()),
                ('max_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='caso.caso4')),
            ],
        ),
    ]
